### ISSUE TITLE
[doc] want  to Complete this process in GitHub(using markdown)

### ISSUE THREAD

**Issue by REHAN-18** [c0sm0void/ReVot#105]
**Is your feature request related to a problem? Please describe.**

like this I want to add in the readme which help the contributor to understand the process (is will be done by markdown with functional like zoom up work, downward etc .. we can control )
<img width="847" alt="Screenshot 2024-10-26 at 12 23 23 AM" src="https://github.com/user-attachments/assets/07f4d1a3-fa00-4dfa-84f6-a914fa718c50">

pls assign me @c0sm0void !!

**Comment by c0sm0void** [comment]
@REHAN-18 assigned
