### ISSUE TITLE
ReVot wiki

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#12]
Document each and every step of this project, from a general overview, requirement, tech stack, working, implementation, and reference.
Please have a look at the attached PDF.
[ReVot.pdf](https://github.com/user-attachments/files/17228823/ReVot.pdf)

**Comment by AKSHITHA-CHILUKA** [comment]
I can do assign it to me

**Comment by c0sm0void** [comment]
@AKSHITHA-CHILUKA assigned

**Comment by AKSHITHA-CHILUKA** [comment]
its my first time editing in wiki so any doubts I will post them here

**Comment by c0sm0void** [comment]
https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis

**Comment by AKSHITHA-CHILUKA** [comment]
Once can you check the page I have added few contents

**Comment by c0sm0void** [comment]
looks good till now. Please remove the source code section, it's not required in wiki page to show code.

**Comment by AKSHITHA-CHILUKA** [comment]
Anything else? should i add

**Comment by c0sm0void** [comment]
Will let you know soon.

**Comment by AKSHITHA-CHILUKA** [comment]
okay !

**Comment by c0sm0void** [comment]
Thanks @AKSHITHA-CHILUKA . looks good!
