### ISSUE TITLE
Add a CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by whyvineet** [c0sm0void/ReVot#14]
Currently, the project lacks a `CODE_OF_CONDUCT.md` file. A Code of Conduct is important to outline the expected behavior for contributors and ensure a welcoming environment for everyone involved. It helps to address any issues that arise from misconduct and sets clear guidelines on how to report such behaviour.

### Task:
- Create a CODE_OF_CONDUCT.md file in the root directory of the project.
- Include a clear set of guidelines for expected behaviour.
- Provide steps for reporting violations.
- Consider using a well-known template like the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).

**Comment by tharun634** [comment]
Hey, I'd like to work on this!

**Comment by whyvineet** [comment]
> Hey, I'd like to work on this!

Assigned to @tharun634
