### ISSUE TITLE
Enhancing Readme.md file

### ISSUE THREAD

**Issue by souvikpramanikgit** [c0sm0void/ReVot#21]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file. Here are a few ideas I have in mind:

I want to add some animations (icons), change the alignment of text and few more changes...

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by c0sm0void** [comment]
@souvikpramanikgit assigned.

**Comment by c0sm0void** [comment]
@souvikpramanikgit please update it as per latest changes in the repo.

**Comment by souvikpramanikgit** [comment]
why level 0 , it will be level 1

**Comment by souvikpramanikgit** [comment]
> @souvikpramanikgit please update it as per latest changes in the repo.

yeah i know.

**Comment by c0sm0void** [comment]
as per recent guidelines by GSSOC, documentation has limits now. Will make it level 1. but later-on no level for this in this repo.

**Comment by souvikpramanikgit** [comment]
> @souvikpramanikgit please update it as per latest changes in the repo.

It will automatically change.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please the issue to me?

**Comment by c0sm0void** [comment]
> I want to work on it. Can you please the issue to me?

it's already assigned to someone else. please create a new issue if there is any enhancement. Documentation are limited as per GSSOC guideline.
