### ISSUE TITLE
Whenever a user sends a picture or gifs to Telegram bot, it throws below error.

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#23]
**Describe the bug**
Whenever a user sends a picture or GIF to the Telegram bot, it throws the below error.

**To Reproduce**
It's a live bug.

**Expected behaviour**
It should provide the result with the search and links per the uploaded data.

**Screenshots**
![image](https://github.com/user-attachments/assets/cbaca279-559c-42f0-810f-a99551527d5f)
![image](https://github.com/user-attachments/assets/cba7e306-41b7-4fc2-b4ce-09ff2911a44a)

**Error msg**
Traceback (most recent call last):
  File "/home/vboxuser/myenv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1335, in process_update
    await coroutine
  File "/home/vboxuser/myenv/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/Desktop/ReVot/reverse_image_search_bot/commands.py", line 135, in image_search_link
    await file.download_to_memory(destination=image_buffer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: File.download_to_memory() got an unexpected keyword argument 'destination'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vboxuser/myenv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1908, in process_error
    await callback(update, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: error() missing 1 required positional argument: 'error'

**Comment by c0sm0void** [comment]
@toxic-for-code assigned.

**Comment by harish08102004** [comment]
Hey @c0sm0void I can work on this.

**Comment by c0sm0void** [comment]
> Hey @c0sm0void I can work on this.

This is assigned to someone else please check other issue.

**Comment by c0sm0void** [comment]
It looks like this issue is fixed already. I am closing it.

**Comment by c0sm0void** [comment]
It looks like this issue is fixed already. I am closing it.
