### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [c0sm0void/ReVot#24]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by c0sm0void** [comment]
@Shariq2003 assigned.

**Comment by Shariq2003** [comment]
@c0sm0void thanks

**Comment by c0sm0void** [comment]
as per recent guidelines by GSSOC, documentation has limits now. Will make it level 1. but later-on no level for this in this repo.
