### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [c0sm0void/ReVot#29]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @c0sm0void please assign this task to me with level tag

**Comment by whyvineet** [comment]
A PR by [souvikpramanikgit](https://github.com/souvikpramanikgit) already exists for the same! #27

**Comment by c0sm0void** [comment]
closing this as this is an existing issue assigned to another contributor.

**Comment by shubhagarwal1** [comment]
> closing this as this is an existing issue assigned to another contributor.

can i work on auto labeler which will add auto labels to the new raised issues and Pr

**Comment by shubhagarwal1** [comment]
> > closing this as this is an existing issue assigned to another contributor.
> 
> can i work on auto labeler which will add auto labels to the new raised issues and Pr
@c0sm0void

**Comment by c0sm0void** [comment]
@shubhagarwal1 sure please create a new issue with this.
