### ISSUE TITLE
README enhancements

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#31]
1. add badges to show, no# of stars, forks, watching --add more if you think needed.
2. add a section where you can show activities - recent 5  issues closed or opened, PRs pending or approved --creativity is your choice, you can use animated stats, graphs etc.
3. add a section to show contributions to this repo -- again creativity is yours, using animated graphs.

**Comment by Emilio-PdeA** [comment]
Hello @c0sm0void, I would like to work in this task to enhance the README file. Can you assign this task to me?

**Comment by c0sm0void** [comment]
@Emilio-PdeA assigned.
