### ISSUE TITLE
Feature:  Rate Limiting

### ISSUE THREAD

**Issue by smog-root** [c0sm0void/ReVot#33]
Depending on the bot's usage, you might want to implement rate limiting to prevent spam or abuse.

I can add a rate limiter by Using a Simple In-Memory Rate Limiter. (OR)  using libraries like ratelimiter.

(or) I can use a Persistent Store (Hard method).

i'm expecting a gssoc-ext and a level3 label.

Assign me! @c0sm0void .

**Comment by c0sm0void** [comment]
@whyvineet @mvp-2003  please look at what level should be applicable. And assign to @smog-root

**Comment by whyvineet** [comment]
> Depending on the bot's usage, you might want to implement rate limiting to prevent spam or abuse.
> 
> I can add a rate limiter by Using a Simple In-Memory Rate Limiter. (OR) using libraries like ratelimiter.
> 
> (or) I can use a Persistent Store (Hard method).
> 
> i'm expecting a gssoc-ext and a level3 label.
> 
> Assign me! @c0sm0void .

Currently, we can assign you `level2` but It can be upgraded to `level3` according to your work!

**Comment by smog-root** [comment]
@mvp-2003 what's your discord?
