### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [c0sm0void/ReVot#45]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @c0sm0void I can work on this.

**Comment by c0sm0void** [comment]
@harish08102004 assigned

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me
