### ISSUE TITLE
Auto labeler workflow failing

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#48]
Make it handle all kind of scenarios
![image](https://github.com/user-attachments/assets/2a011316-f461-4514-89a8-184ae950e64f)

**Comment by c0sm0void** [comment]
@mvp-2003 .github/workflows/labeler.yml

**Comment by toxic-for-code** [comment]
PR is created for this please assign

**Comment by c0sm0void** [comment]
> PR is created for this please assign

only work on issue if assigned not before @toxic-for-code
