### ISSUE TITLE
README.md workflow not properly working

### ISSUE THREAD

**Issue by mvp-2003** [c0sm0void/ReVot#49]
Pretty much self-explanatory

**Comment by c0sm0void** [comment]
@mvp-2003 ????

**Comment by mvp-2003** [comment]
So as of now, it's pretty much safe to say that none of the workflows are working.

**Comment by c0sm0void** [comment]
> So as of now, it's pretty much safe to say that none of the workflows are working.

omg!

**Comment by c0sm0void** [comment]
@mvp-2003 someone create a PR for fix, look into it

**Comment by whyvineet** [comment]
Guys I have been looking for that for the past few hours and I think if we delete the `[update-readme.yml](https://github.com/c0sm0void/ReVot/blob/master/.github/workflows/update-readme.yml)` file then it can be resolved! And I don't think it affects anything!

**Comment by c0sm0void** [comment]
try it. I don't have much idea on workflows.

**Comment by c0sm0void** [comment]
@whyvineet @mvp-2003 i have removed the update-readme.yml, and updated the rest of workflow. Its working now properly
