### ISSUE TITLE
some major improvements in reverse_image_search_bot/commands.py

### ISSUE THREAD

**Issue by bhavya2021245** [c0sm0void/ReVot#55]
**Describe the bug**
The Reverse Image Search Bot exhibits several issues that hinder its performance, reliability, and maintainability. The primary areas of concern are:

1.Asynchronous Handling for Improved Performance
Issue: The bot currently mixes asynchronous (async def) and synchronous functions. Functions like gif_image_search, sticker_image_search, and others are synchronous, which can block the event loop and degrade performance, especially under high load or when handling multiple requests simultaneously.

2.Error Handling and Input Validation
Issue: The bot lacks comprehensive error handling and input validation. Critical sections of the code use functions like os.system without verifying their success, and there's minimal validation of user inputs. This can lead to unexpected crashes, security vulnerabilities, and a poor user experience.

3.Code Organization and Modularity
Issue: The current codebase does not adhere to the Single Responsibility Principle. Functions handle multiple responsibilities, such as image processing, search logic, and Telegram interactions all within the same functions. This makes the code harder to maintain, extend, and test.

**To Reproduce**

1.Asynchronous Handling Issue:
Step 1: Deploy the bot and initiate multiple reverse image search requests simultaneously.
Step 2: Monitor the bot's responsiveness and resource usage.
Step 3: Observe any delays or unresponsiveness due to blocking synchronous operations.

2.Error Handling and Input Validation Issue:
Step 1: Send various malformed or unsupported files (e.g., non-image files) to the bot.
Step 2: Attempt to trigger external command failures (e.g., by removing gifsicle from the server).
Step 3: Observe how the bot handles these scenarios without crashing or providing informative error messages.

3.Code Organization and Modularity Issue:
Step 1: Navigate through the codebase, focusing on functions like general_image_search.
Step 2: Attempt to modify or extend specific functionalities, such as adding a new search engine.
Step 3: Experience difficulties due to tightly coupled components and overlapping responsibilities.

**Expected behavior**
1.Asynchronous Handling for Improved Performance:
All handler functions should be fully asynchronous, utilizing non-blocking operations to enhance the bot's responsiveness and scalability. The bot should efficiently handle multiple simultaneous requests without performance degradation.

2.Error Handling and Input Validation:
The bot should gracefully handle exceptions and provide informative error messages to users. It should validate all user inputs to ensure they meet expected formats and types, preventing crashes and enhancing security.

3.Code Organization and Modularity:
The codebase should follow the Single Responsibility Principle, separating concerns into distinct modules or classes. This refactoring will improve readability, maintainability, and facilitate easier testing and future feature additions.

**Comment by omkar-sarwat** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by c0sm0void** [comment]
@bhavya2021245 assigned.

**Comment by c0sm0void** [comment]
> I would like to work on this issue. Can you please assign it to me?

@omkar-sarwat this is raised by other contributor, please look for another issue

**Comment by c0sm0void** [comment]
@bhavya2021245 please get the latest code and start your changes please.

**Comment by bhavya2021245** [comment]
Thanks @c0sm0void for assigning me this issue
Will surely do it by end of day.
