### ISSUE TITLE
Python base upgrade from v3.6 to v3.12.

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#6]
**Is your feature request related to a problem? Please describe.**
We now have the latest Python v3.12 and would like to upgrade the project base.
Check all scripts and dependencies too.

**Describe alternatives you've considered**
Suggest changes if anyone wants to do them one by one rather than changing the whole project base.

**Comment by trishap-16** [comment]
I would like to work on this issue @c0sm0void

**Comment by c0sm0void** [comment]
@trishap-16 assigned.
Please reach out to project mentos for any guidance @whyvineet @mvp-2003

**Comment by c0sm0void** [comment]
Hi @trishap-16 , I can see with the latest 3.12 it's not compatible especially as it used virtual Python space to work in 3.6.
Could you please make every script and requirement compatible, in that case, we can make it level 3?
