### ISSUE TITLE
Out of curiosity - wanted to know why the values are not updating in README file.

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#69]

**Comment by c0sm0void** [comment]
![375964768-c36a9cb2-a9c2-4267-a744-dbb0dce27ffe](https://github.com/user-attachments/assets/6423dfae-4e76-42e3-bfc0-7d5e338ab140)

**Comment by whyvineet** [comment]
`update-readme.yml` is not available in `.github/workflows` directory! Have you deleted the file?

**Comment by c0sm0void** [comment]
> `update-readme.yml` is not available in `.github/workflows` directory! Have you deleted the file?

Yes that file was for updating recent activities in readme. That is not needed.

**Comment by whyvineet** [comment]
> > `update-readme.yml` is not available in `.github/workflows` directory! Have you deleted the file?
> 
> Yes that file was for updating recent activities in readme. That is not needed.

That's also updating these issues, pr, and contribution count!

**Comment by c0sm0void** [comment]
@whyvineet nah bro, that have no link to this. I think so. Because if you go to the badge hyperlink 
It is showing the value
![Screenshot_20241014-224154.png](https://github.com/user-attachments/assets/aba5a386-496b-4494-9b0c-fbd03e61d371)

**Comment by whyvineet** [comment]
@c0sm0void merge PR #89 as it resolves the issue

**Comment by c0sm0void** [comment]
Great thanks 👍
