### ISSUE TITLE
update readme.md file

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [c0sm0void/ReVot#7]
Add more details about the project , guidelines ,license and how to contribute

(Please add gssoc-ext 24 and hacktoberfest label)

**Comment by c0sm0void** [comment]
@AKSHITHA-CHILUKA assigned.

**Comment by trishap-16** [comment]
Can you assign this issue to me

**Comment by AKSHITHA-CHILUKA** [comment]
Sorry I have already completed it @trishap-16

**Comment by c0sm0void** [comment]
@trishap-16 @AKSHITHA-CHILUKA 
Please let me know if you want to take up https://github.com/c0sm0void/ReVot/issues/12

**Comment by AKSHITHA-CHILUKA** [comment]
I can take up #12

**Comment by c0sm0void** [comment]
@HackesticMedusa it's already assigned to someone else. Please look for or create new issue which are not assigned to anyone.
