### ISSUE TITLE
Documentation: Add Table of Contents in README file

### ISSUE THREAD

**Issue by Maryam0330** [c0sm0void/ReVot#71]
**Is your feature request related to a problem? Please describe.**
If the `Table of Contents` is not present in the README file, it can make navigating through the project a bit challenging for users. Without a clear structure or easy access to key sections, users may find it time-consuming to locate specific information or understand the flow of the project.

**Describe the solution you'd like**
By adding a `Table of Contents`, you ensure that users can quickly find what they are looking for, improving overall accessibility and user experience.

**Comment by Maryam0330** [comment]
Please assign me this task under `gssoc-ext` and `hacktoberfest-accepted` label.

**Comment by c0sm0void** [comment]
@Maryam0330 assigned. Please think of more content or changes to get approval for level1.
