### ISSUE TITLE
Local server setup in single board computer or traditional system.

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#8]
**Is your feature request related to a problem? Please describe.**
Currently the subscription charges of running virtual machine on MS Azure for this project isn't much budget friendly. 

**Describe the solution you'd like**
To make the server locally installed in a single board computer or traditional system.

**Additional context**
Linux will be best in single board computer and with network and firewall setup to enhance data security and privacy.

**Comment by AHSANATIQ98** [comment]
"I'd like to work on this issue. Could you please assign it to me?
