### ISSUE TITLE
Add Debian-Based Distros Specification to README

### ISSUE THREAD

**Issue by 5odead** [c0sm0void/ReVot#85]
### Is your feature request related to a problem? Please describe.
Many users may attempt to install or run this project on non-Debian-based Linux distributions, which could lead to confusion and installation failures. 

### Describe the solution you'd like
I would like the project owner to explicitly mention in the README that this project is intended solely for Debian-based distributions. 

### Describe alternatives you've considered
An alternative would be to write code supported by all Linux distributions. 

### Additional context
Including this information in the README will enhance user experience and prevent confusion that the command in pre-installation.sh are for debian based distros

**Comment by c0sm0void** [comment]
@5odead assigned. Please add installation steps for Windows users too.
