### ISSUE TITLE
enhance readme 

### ISSUE THREAD

**Issue by Aditijainnn** [c0sm0void/ReVot#88]
In readme adding contributors profile and go to top toggle button
assign this to me under gssoc ext

**Comment by Aditijainnn** [comment]
> @Aditijainnn please suggest more if you can add in readme. With your suggested change I can assign only level0. Let me know if you ok with it.

usually its for level 1

**Comment by c0sm0void** [comment]
> > @Aditijainnn please suggest more if you can add in readme. With your suggested change I can assign only level0. Let me know if you ok with it.
> 
> usually its for level 1

@Aditijainnn yes but as per latest guideline it should be little more to get level1. Think of something more then can give level1 to it🙏

**Comment by c0sm0void** [comment]
> @Aditijainnn please assign this issue to me

@smartfellow1234 it is assigned to @Aditijainnn . Please look for other issue.
