### ISSUE TITLE
Have Whatsapp bot integration (if possible).

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#9]
**Is your feature request related to a problem? Please describe.**
This is only limited to Telegram bot due to its high configuration and integration.

**Describe the solution you'd like**
Would like to integrate with WhatsApp bot (if possible).

**Comment by amannaik247** [comment]
Hi can you give me some more info on how I can solve this issue. I wish to contribute here . A few starting steps on how I should go about this would be helpful. Thank you!

**Comment by c0sm0void** [comment]
Well this is something difficult to integrate, as it will require skill set like node.js, multiple 3rd party integration and many more.
Apologies for this issue. Will be revoking this due to high complexity.
Thanks for your interest 🙂
