### ISSUE TITLE
Adding github action workflow for PR validation

### ISSUE THREAD

**Issue by ygowthamr** [c0sm0void/ReVot#91]
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@c0sm0void
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

**Comment by c0sm0void** [comment]
@ygowthamr assigned.

**Comment by ygowthamr** [comment]
Thank
