### ISSUE TITLE
Auto labeler workflow issue

### ISSUE THREAD

**Issue by c0sm0void** [c0sm0void/ReVot#93]
Sometimes it works sometimes don't. Please look for the actual cause and provide a fix for this. 
Especially not working for pull requests.
Earlier fix: #72
![Screenshot_20241017-204337.png](https://github.com/user-attachments/assets/fd5a28a5-f98f-44e6-8ea6-ce051c5b5278)

**Comment by OmmDevgoswami** [comment]
Please assign me this Issue

**Comment by c0sm0void** [comment]
@OmmDevgoswami  assigned
