### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [c0sm0void/ReVot#95]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @c0sm0void 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by c0sm0void** [comment]
@smog-root assigned. Level 2 because some implementations already present.

**Comment by smog-root** [comment]
@c0sm0void okay!! Level2 is fine!!
