### ISSUE TITLE
Auto labeling github action is not working on you'r repo!!

### ISSUE THREAD

**Issue by smog-root** [c0sm0void/ReVot#98]
I have noticed that the labeler.yml is not functioning well!!

I can fix that!! 

**Add gssoc-ext with level and hacktoberfeast-accepted labels** @c0sm0void 

![Screenshot 2024-10-22 074422](https://github.com/user-attachments/assets/457aa641-23d4-406e-89a9-e76c9569a3c1)

**Comment by c0sm0void** [comment]
@smog-root assigned. 
Note that this issue is failing for only on PR, not on issues

**Comment by smog-root** [comment]
@c0sm0void okay!!

**Comment by smog-root** [comment]
i'm currently not work on workflows!
